bucket_no_upscale = true
bucket_reso_steps = 256
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 2
dynamo_backend = "no"
enable_bucket = true
epoch = 30
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
logging_dir = "D:/model_output/log"
loss_type = "l2"
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 225
max_train_epochs = 30
metadata_author = "motimalu"
min_bucket_reso = 512
min_snr_gamma = 5
mixed_precision = "bf16"
multires_noise_discount = 0.3
multires_noise_iterations = 6
network_alpha = 32
network_args = []
network_dim = 32
network_module = "networks.lora"
no_half_vae = true
noise_offset_type = "Multires"
optimizer_args = []
optimizer_type = "Prodigy"
output_dir = "D:/model_output"
output_name = "collection_name_v1"
pretrained_model_name_or_path = "C:/workspace/webui_forge_cu121_torch21/webui/models/Stable-diffusion/illustriousXL_v01.safetensors"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = "D:/model_output/sample/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 5
save_model_as = "safetensors"
save_precision = "bf16"
seed = 339491249
text_encoder_lr = 1
train_batch_size = 6
train_data_dir = "C:/data/collection_name"
unet_lr = 1
xformers = true